# Generated by Django 3.2.4 on 2021-06-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('media', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
